#!/usr/bin/env bash
CXX=clang++
CC=clang
BUILD_DIR=.build
BUILD_TYPE=Debug

CONAN_PROFILE=default
if [[ "${BUILD_TYPE}" == "Debug" ]]; then
    CONAN_PROFILE="debug"
fi

conan install . -of ${BUILD_DIR} -pr ${CONAN_PROFILE} --build missing
source ${BUILD_DIR}/conanbuild.sh

cmake -H. -B${BUILD_DIR} -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC} -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_INSTALL_PREFIX=./
cmake --build ${BUILD_DIR}
